// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-28k7rWdQPNHOHGvP3AcBulud250qAk',
    appId: '1:343685253973:web:54c120e4e9785a273d3ddc',
    messagingSenderId: '343685253973',
    projectId: 'flutterproject-4c80e',
    authDomain: 'flutterproject-4c80e.firebaseapp.com',
    storageBucket: 'flutterproject-4c80e.firebasestorage.app',
    measurementId: 'G-6RCJW6CBQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAyOWgRt1M5yrDM3GdVhaGkpfZeRWKrdA',
    appId: '1:343685253973:android:44d344c635351c933d3ddc',
    messagingSenderId: '343685253973',
    projectId: 'flutterproject-4c80e',
    storageBucket: 'flutterproject-4c80e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuY3xZ0aeWaKNcW_Tw1oA0XtNwcv7RCZA',
    appId: '1:343685253973:ios:b30f372a57bb43e93d3ddc',
    messagingSenderId: '343685253973',
    projectId: 'flutterproject-4c80e',
    storageBucket: 'flutterproject-4c80e.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuY3xZ0aeWaKNcW_Tw1oA0XtNwcv7RCZA',
    appId: '1:343685253973:ios:b30f372a57bb43e93d3ddc',
    messagingSenderId: '343685253973',
    projectId: 'flutterproject-4c80e',
    storageBucket: 'flutterproject-4c80e.firebasestorage.app',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs-28k7rWdQPNHOHGvP3AcBulud250qAk',
    appId: '1:343685253973:web:c38014f744cc35d03d3ddc',
    messagingSenderId: '343685253973',
    projectId: 'flutterproject-4c80e',
    authDomain: 'flutterproject-4c80e.firebaseapp.com',
    storageBucket: 'flutterproject-4c80e.firebasestorage.app',
    measurementId: 'G-X2MF3N4BMX',
  );

}